-- item table
CREATE TABLE IF NOT EXISTS item
(
    id integer
        constraint item_pk
        primary key autoincrement,
    name text not null,
    description text not null
);

INSERT INTO item (name, description) VALUES
      ('Master Ball', 'A Ball that captures any wild Pokémon without fail.'),
      ('Ultra Ball', 'A Ball for catching wild Pokémon. More effective than a Great Ball.'),
      ('Great Ball', 'A Ball for catching wild Pokémon. More effective than a Poké Ball.'),
      ('Poké Ball', 'A Ball thrown at wild Pokémon to catch them.'),
      ('Town Map', 'A map of the local area. It identifies your present location.'),
      ('Bicycle', 'Lets you travel twice as fast as walking.'),
      ('Safari Ball', 'A Ball used in the Safari Zone for catching wild Pokémon.'),
      ('Moon Stone', 'A Stone used for making certain kinds of Pokémon evolve.'),
      ('Antidote', 'An antidote for curing a poisoned Pokémon.'),
      ('Burn Heal', 'Medicine for curing a Pokémon that is suffering from burn.'),
      ('Ice Heal', 'Thaws out a Pokémon that has been frozen solid.'),
      ('Awakening', 'Awakens a Pokémon that has fallen asleep.'),
      ('Parlyz Heal', 'Cures a Pokémon that is suffering from paralysis.'),
      ('Full Restore', 'Fully restores HP and cures all ailments, such as poisoning.'),
      ('Max Potion', 'Fully restores HP that have been lost in battle.'),
      ('Hyper Potion', 'Restores HP that have been lost in battle by 200 HP.'),
      ('Super Potion', 'Restores HP that have been lost in battle by 50 HP.'),
      ('Potion', 'Restores HP that have been lost in battle by 20 HP.'),
      ('Escape Rope', 'When in a place like a cave, this returns you to the last Pokémon Center visited.'),
      ('Repel', 'An aerosol spray that keeps wild Pokémon away.'),
      ('Old Amber', 'The fossilized resin of a tree from prehistoric trees.'),
      ('Fire Stone', 'A Stone used for making certain kinds of Pokémon evolve.'),
      ('Thunderstone', 'A Stone used for making certain kinds of Pokémon evolve.'),
      ('Water Stone', 'A Stone used for making certain kinds of Pokémon evolve.'),
      ('HP Up', 'Increases the maximum HP of the selected Pokémon.'),
      ('Protein', 'Increases the Attack power of the selected Pokémon.'),
      ('Iron', 'Increases the Defense rating of the selected Pokémon.'),
      ('Carbos', 'Increases the Speed of the selected Pokémon.'),
      ('Calcium', 'Increases the Special rating of the selected Pokémon.'),
      ('Rare Candy', 'Raises the level of the selected Pokémon by one.'),
      ('Dome Fossil', 'A fossil of a Pokémon that lived in prehistoric times.'),
      ('Helix Fossil', 'A fossil of a Pokémon that lived in prehistoric times.'),
      ('Secret Key', 'The key required to enter a Pokémon Gym somewhere.'),
      ('Bike Voucher', 'To be exchanged for a Bike at the Bike Shop in Cerulean City.'),
      ('X Accuracy', 'Temporarily heightens accuracy for one battle.'),
      ('Leaf Stone', 'A Stone used for making certain kinds of Pokémon evolve.'),
      ('Card Key', 'The security card key for opening doors in a certain building.'),
      ('Nugget', 'Can be sold for a very good price at any Pokémon Mart.'),
      ('Poké Doll', 'Use during a battle against a wild Pokémon to make a getaway.'),
      ('Full Heal', 'Cures a Pokémon of any ailment except for fainting.'),
      ('Revive', 'Revives a fainted Pokémon and restores half its maximum HP.'),
      ('Max Revive', 'Revives a fainted Pokémon, fully restoring its HP.'),
      ('Guard Spec.', 'Temporarily increases Speed for one battle.'),
      ('Super Repel', 'Keeps wild Pokémon away. Longer lasting than Repel.'),
      ('Max Repel', 'Keeps wild Pokémon away. Longer lasting than Super Repel.'),
      ('Dire Hit', 'Temporarily heightens the probability of scoring critical hits in one battle.'),
      ('Fresh Water', 'Restores HP that have been lost in battle by 50 HP.'),
      ('Soda Pop', 'Restores HP that have been lost in battle by 60 HP.'),
      ('Lemonade', 'Restores HP that have been lost in battle by 80 HP.'),
      ('S.S. Ticket', 'The invitation card required to board the luxury liner, S.S. Anne.'),
      ('Gold Teeth', 'Apparently lost and desperately sought by the Safari Zone Warden.'),
      ('X Attack', 'Temporarily increases Attack power for one battle.'),
      ('X Defend', 'Temporarily increases Defense for one battle.'),
      ('X Speed', 'Temporarily increases Speed for one battle.'),
      ('X Special', 'Temporarily increases Special for one battle.'),
      ('Coin Case', 'Required for playing slot machines. Up to 9,999 coins may be carried.'),
      ('Oak''s Parcel', 'A parcel from a Pokémon Mart for delivery to Prof. Oak.'),
      ('Itemfinder', 'A machine for searching items on the ground.'),
      ('Silph Scope', 'An item that makes ghosts clearly distinguishable.'),
      ('Poké Flute', 'Plays a pleasant melody that rouses Pokémon from sleep.'),
      ('Lift Key', 'The key used for operating the elevator in a certain building.'),
      ('Exp. All', 'Gives Exp. Points to all Pokémon in party, even those not in battle.'),
      ('Old Rod', 'Use in front of the sea, a river, etc., to fish for Pokémon.'),
      ('Good Rod', 'Use in front of the sea, a river, etc., to fish for Pokémon.'),
      ('Super Rod', 'Use in front of the sea, a river, etc., to fish for Pokémon.'),
      ('PP Up', 'Increases the PP of the selected move by 20 percent.'),
      ('Ether', 'Restores the PP of the selected move by 10.'),
      ('Max Ether', 'Fully restores the PP of the selected move.'),
      ('Elixer', 'Restores the PP of all the selected Pokémon''s moves by 10.'),
      ('Max Elixer', 'Fully restores the PP of all the selected Pokémon''s moves.'),
      ('HM01', 'Teaches Cut'),
      ('HM02', 'Teaches Fly'),
      ('HM03', 'Teaches Surf'),
      ('HM04', 'Teaches Strength'),
      ('HM05', 'Teaches Flash'),
      ('TM01', 'Teaches Mega Punch'),
      ('TM02', 'Teaches Razor Wind'),
      ('TM03', 'Teaches Swords Dance'),
      ('TM04', 'Teaches Whirlwind'),
      ('TM05', 'Teaches Mega Kick'),
      ('TM06', 'Teaches Toxic'),
      ('TM07', 'Teaches Horn Drill'),
      ('TM08', 'Teaches Body Slam'),
      ('TM09', 'Teaches Take Down'),
      ('TM10', 'Teaches Double-Edge'),
      ('TM11', 'Teaches BubbleBeam'),
      ('TM12', 'Teaches Water Gun'),
      ('TM13', 'Teaches Ice Beam'),
      ('TM14', 'Teaches Blizzard'),
      ('TM15', 'Teaches Hyper Beam'),
      ('TM16', 'Teaches Pay Day'),
      ('TM17', 'Teaches Submission'),
      ('TM18', 'Teaches Counter'),
      ('TM19', 'Teaches Seismic Toss'),
      ('TM20', 'Teaches Rage'),
      ('TM21', 'Teaches Mega Drain'),
      ('TM22', 'Teaches SolarBeam'),
      ('TM23', 'Teaches Dragon Rage'),
      ('TM24', 'Teaches Thunderbolt'),
      ('TM25', 'Teaches Thunder'),
      ('TM26', 'Teaches Earthquake'),
      ('TM27', 'Teaches Fissure'),
      ('TM28', 'Teaches Dig'),
      ('TM29', 'Teaches Psychic'),
      ('TM30', 'Teaches Teleport'),
      ('TM31', 'Teaches Mimic'),
      ('TM32', 'Teaches Double Team'),
      ('TM33', 'Teaches Reflect'),
      ('TM34', 'Teaches Bide'),
      ('TM35', 'Teaches Metronome'),
      ('TM36', 'Teaches Selfdestruct'),
      ('TM37', 'Teaches Egg Bomb'),
      ('TM38', 'Teaches Fire Blast'),
      ('TM39', 'Teaches Swift'),
      ('TM40', 'Teaches Skull Bash'),
      ('TM41', 'Teaches Softboiled'),
      ('TM42', 'Teaches Dream Eater'),
      ('TM43', 'Teaches Sky Attack'),
      ('TM44', 'Teaches Rest'),
      ('TM45', 'Teaches Thunder Wave'),
      ('TM46', 'Teaches Psywave'),
      ('TM47', 'Teaches Explosion'),
      ('TM48', 'Teaches Rock Slide'),
      ('TM49', 'Teaches Tri Attack'),
      ('TM50', 'Teaches Substitute');
