--- Move table
CREATE TABLE IF NOT EXISTS move
(
    id
        integer
        constraint move_pk
            primary key autoincrement,
    name
        text
        not null,
    pp
        integer
        not null,
    power
        integer,
    accuracy
        integer,
    type_id
        integer
        not null
        constraint
            move_type_id_fk
            references
                type
);

INSERT INTO move (name, power, accuracy, pp, type_id) VALUES
    ('Absorb', 20, 100, 20, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Acid', 40, 100, 30, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Acid Armor', null, null, 40, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Agility', null, null, 30, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Amnesia', null, null, 20, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Aurora Beam', 65, 100, 20, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Barrage', 15, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Barrier', null, null, 30, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Bide', null, null, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Bind', 15, 75, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Bite', 60, 100, 25, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Blizzard', 120, 90, 5, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Body Slam', 85, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Bone Club', 65, 85, 20, (SELECT id FROM type WHERE type.name = 'Ground')),
    ('Bonemerang', 50, 90, 10, (SELECT id FROM type WHERE type.name = 'Ground')),
    ('Bubble', 20, 100, 30, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Bubble Beam', 65, 100, 20, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Clamp', 35, 75, 10, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Comet Punch', 18, 85, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Confuse Ray', null, 100, 10, (SELECT id FROM type WHERE type.name = 'Ghost')),
    ('Confusion', 50, 100, 25, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Constrict', 10, 100, 35, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Conversion', null, null, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Counter', 1, 100, 20, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Crabhammer', 90, 85, 10, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Cut', 50, 95, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Defense Curl', null, null, 40, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Dig', 100, 100, 10, (SELECT id FROM type WHERE type.name = 'Ground')),
    ('Disable', null, 55, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Dizzy Punch', 70, 100, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Double Kick', 30, 100, 30, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Double Slap', 15, 85, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Double Team', null, null, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Double-Edge', 100, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Dragon Rage', 1, 100, 10, (SELECT id FROM type WHERE type.name = 'Dragon')),
    ('Dream Eater', 100, 100, 15, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Drill Peck', 80, 100, 20, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Earthquake', 100, 100, 10, (SELECT id FROM type WHERE type.name = 'Ground')),
    ('Egg Bomb', 100, 75, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Ember', 40, 100, 25, (SELECT id FROM type WHERE type.name = 'Fire')),
    ('Explosion', 170, 100, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Fire Blast', 120, 85, 5, (SELECT id FROM type WHERE type.name = 'Fire')),
    ('Fire Punch', 75, 100, 15, (SELECT id FROM type WHERE type.name = 'Fire')),
    ('Fire Spin', 15, 70, 15, (SELECT id FROM type WHERE type.name = 'Fire')),
    ('Fissure', null, 30, 5, (SELECT id FROM type WHERE type.name = 'Ground')),
    ('Flamethrower', 95, 100, 15, (SELECT id FROM type WHERE type.name = 'Fire')),
    ('Flash', null, 70, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Fly', 70, 95, 15, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Focus Energy', null, null, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Fury Attack', 15, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Fury Swipes', 18, 80, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Glare', null, 75, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Growl', null, 100, 40, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Growth', null, null, 40, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Guillotine', null, 30, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Gust', 40, 100, 35, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Harden', null, null, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Haze', null, null, 30, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Headbutt', 70, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('High Jump Kick', 85, 90, 20, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Horn Attack', 65, 100, 25, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Horn Drill', null, 30, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Hydro Pump', 120, 80, 5, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Hyper Beam', 150, 90, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Hyper Fang', 80, 90, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Hypnosis', null, 60, 20, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Ice Beam', 95, 100, 10, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Ice Punch', 75, 100, 15, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Jump Kick', 70, 95, 25, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Karate Chop', 50, 100, 25, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Kinesis', null, 80, 15, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Leech Life', 20, 100, 15, (SELECT id FROM type WHERE type.name = 'Bug')),
    ('Leech Seed', null, 90, 10, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Leer', null, 100, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Lick', 20, 100, 30, (SELECT id FROM type WHERE type.name = 'Ghost')),
    ('Light Screen', null, null, 30, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Lovely Kiss', null, 75, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Low Kick', 50, 90, 20, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Meditate', null, null, 40, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Mega Drain', 40, 100, 10, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Mega Kick', 120, 75, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Mega Punch', 80, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Metronome', null, null, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Mimic', null, 100, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Minimize', null, null, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Mirror Move', null, null, 20, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Mist', null, null, 30, (SELECT id FROM type WHERE type.name = 'Ice')),
    ('Night Shade', 1, 100, 15, (SELECT id FROM type WHERE type.name = 'Ghost')),
    ('Pay Day', 40, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Peck', 35, 100, 35, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Petal Dance', 70, 100, 20, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Pin Missile', 14, 85, 20, (SELECT id FROM type WHERE type.name = 'Bug')),
    ('Poison Gas', null, 55, 40, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Poison Powder', null, 75, 35, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Poison Sting', 15, 100, 35, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Pound', 40, 100, 35, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Psybeam', 65, 100, 20, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Psychic', 90, 100, 10, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Psywave', 1, 80, 15, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Quick Attack', 40, 100, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Rage', 20, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Razor Leaf', 55, 95, 25, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Razor Wind', 80, 75, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Recover', null, null, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Reflect', null, null, 20, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Rest', null, null, 10, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Roar', null, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Rock Slide', 75, 90, 10, (SELECT id FROM type WHERE type.name = 'Rock')),
    ('Rock Throw', 50, 65, 15, (SELECT id FROM type WHERE type.name = 'Rock')),
    ('Rolling Kick', 60, 85, 15, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Sand Attack', null, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Scratch', 40, 100, 35, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Screech', null, 85, 40, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Seismic Toss', 1, 100, 20, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Self-Destruct', 130, 100, 5, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Sharpen', null, null, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Sing', null, 55, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Skull Bash', 100, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Sky Attack', 140, 90, 5, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Slam', 80, 75, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Slash', 70, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Sleep Powder', null, 75, 15, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Sludge', 65, 100, 20, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Smog', 20, 70, 20, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Smokescreen', null, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Soft-Boiled', null, null, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Solar Beam', 120, 100, 10, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Sonic Boom', 1, 90, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Spike Cannon', 20, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Splash', null, null, 40, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Spore', null, 100, 15, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Stomp', 65, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Strength', 80, 100, 15, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('String Shot', null, 95, 40, (SELECT id FROM type WHERE type.name = 'Bug')),
    ('Struggle', 50, 100, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Stun Spore', null, 75, 30, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Submission', 80, 80, 25, (SELECT id FROM type WHERE type.name = 'Fighting')),
    ('Substitute', null, null, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Super Fang', 1, 90, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Supersonic', null, 55, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Surf', 95, 100, 15, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Swift', 60, null, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Swords Dance', null, null, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Tackle', 35, 95, 35, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Tail Whip', null, 100, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Take Down', 90, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Teleport', null, null, 20, (SELECT id FROM type WHERE type.name = 'Psychic')),
    ('Thrash', 90, 100, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Thunder', 120, 70, 10, (SELECT id FROM type WHERE type.name = 'Electric')),
    ('Thunder Punch', 75, 100, 15, (SELECT id FROM type WHERE type.name = 'Electric')),
    ('Thunder Shock', 40, 100, 30, (SELECT id FROM type WHERE type.name = 'Electric')),
    ('Thunder Wave', null, 100, 20, (SELECT id FROM type WHERE type.name = 'Electric')),
    ('Thunderbolt', 95, 100, 15, (SELECT id FROM type WHERE type.name = 'Electric')),
    ('Toxic', null, 85, 10, (SELECT id FROM type WHERE type.name = 'Poison')),
    ('Transform', null, null, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Tri Attack', 80, 100, 10, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Twineedle', 25, 100, 20, (SELECT id FROM type WHERE type.name = 'Bug')),
    ('Vice Grip', 55, 100, 30, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Vine Whip', 35, 100, 10, (SELECT id FROM type WHERE type.name = 'Grass')),
    ('Water Gun', 40, 100, 25, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Waterfall', 80, 100, 15, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Whirlwind', null, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal')),
    ('Wing Attack', 35, 100, 35, (SELECT id FROM type WHERE type.name = 'Flying')),
    ('Withdraw', null, null, 40, (SELECT id FROM type WHERE type.name = 'Water')),
    ('Wrap', 15, 85, 20, (SELECT id FROM type WHERE type.name = 'Normal'))
;
