--- stat table
CREATE TABLE IF NOT EXISTS stat
(
    id
        integer
        constraint stats_pk
            primary key autoincrement,
    monster_id
        integer
        not null
        constraint
            stat_monster_id_fk
            references
                monster,
    height -- the height in inches
        real
        not null,
    weight -- the weight in pounds
        real
        not null
);

INSERT INTO stat (monster_id, height, weight)
VALUES ((SELECT id FROM monster WHERE name = 'Bulbasaur'), 28, 15),
       ((SELECT id FROM monster WHERE name = 'Ivysaur'), 39, 29),
       ((SELECT id FROM monster WHERE name = 'Venusaur'), 79, 221),
       ((SELECT id FROM monster WHERE name = 'Charmander'), 24, 19),
       ((SELECT id FROM monster WHERE name = 'Charmeleon'), 43, 42),
       ((SELECT id FROM monster WHERE name = 'Charizard'), 67, 200),
       ((SELECT id FROM monster WHERE name = 'Squirtle'), 20, 20),
       ((SELECT id FROM monster WHERE name = 'Wartortle'), 39, 50),
       ((SELECT id FROM monster WHERE name = 'Blastoise'), 63, 189),
       ((SELECT id FROM monster WHERE name = 'Caterpie'), 12, 6),
       ((SELECT id FROM monster WHERE name = 'Metapod'), 28, 22),
       ((SELECT id FROM monster WHERE name = 'Butterfree'), 43, 71),
       ((SELECT id FROM monster WHERE name = 'Weedle'), 12, 7),
       ((SELECT id FROM monster WHERE name = 'Kakuna'), 24, 22),
       ((SELECT id FROM monster WHERE name = 'Beedrill'), 39, 65),
       ((SELECT id FROM monster WHERE name = 'Pidgey'), 12, 4),
       ((SELECT id FROM monster WHERE name = 'Pidgeotto'), 43, 66),
       ((SELECT id FROM monster WHERE name = 'Pidgeot'), 59, 87),
       ((SELECT id FROM monster WHERE name = 'Rattata'), 12, 8),
       ((SELECT id FROM monster WHERE name = 'Raticate'), 28, 41),
       ((SELECT id FROM monster WHERE name = 'Spearow'), 12, 4),
       ((SELECT id FROM monster WHERE name = 'Fearow'), 47, 84),
       ((SELECT id FROM monster WHERE name = 'Ekans'), 79, 15),
       ((SELECT id FROM monster WHERE name = 'Arbok'), 138, 143),
       ((SELECT id FROM monster WHERE name = 'Pikachu'), 16, 13),
       ((SELECT id FROM monster WHERE name = 'Raichu'), 31, 66),
       ((SELECT id FROM monster WHERE name = 'Sandshrew'), 24, 26),
       ((SELECT id FROM monster WHERE name = 'Sandslash'), 39, 65),
       ((SELECT id FROM monster WHERE name = 'Nidoran♀'), 16, 15),
       ((SELECT id FROM monster WHERE name = 'Nidorina'), 31, 44),
       ((SELECT id FROM monster WHERE name = 'Nidoqueen'), 51, 132),
       ((SELECT id FROM monster WHERE name = 'Nidoran♂'), 20, 20),
       ((SELECT id FROM monster WHERE name = 'Nidorino'), 35, 43),
       ((SELECT id FROM monster WHERE name = 'Nidoking'), 55, 137),
       ((SELECT id FROM monster WHERE name = 'Clefairy'), 24, 17),
       ((SELECT id FROM monster WHERE name = 'Clefable'), 51, 88),
       ((SELECT id FROM monster WHERE name = 'Vulpix'), 24, 22),
       ((SELECT id FROM monster WHERE name = 'Ninetales'), 43, 44),
       ((SELECT id FROM monster WHERE name = 'Jigglypuff'), 20, 12),
       ((SELECT id FROM monster WHERE name = 'Wigglytuff'), 39, 26),
       ((SELECT id FROM monster WHERE name = 'Zubat'), 31, 17),
       ((SELECT id FROM monster WHERE name = 'Golbat'), 63, 121),
       ((SELECT id FROM monster WHERE name = 'Oddish'), 20, 12),
       ((SELECT id FROM monster WHERE name = 'Gloom'), 31, 19),
       ((SELECT id FROM monster WHERE name = 'Vileplume'), 47, 41),
       ((SELECT id FROM monster WHERE name = 'Paras'), 12, 12),
       ((SELECT id FROM monster WHERE name = 'Parasect'), 39, 65),
       ((SELECT id FROM monster WHERE name = 'Venonat'), 39, 66),
       ((SELECT id FROM monster WHERE name = 'Venomoth'), 59, 28),
       ((SELECT id FROM monster WHERE name = 'Diglett'), 8, 2),
       ((SELECT id FROM monster WHERE name = 'Dugtrio'), 28, 73),
       ((SELECT id FROM monster WHERE name = 'Meowth'), 16, 9),
       ((SELECT id FROM monster WHERE name = 'Persian'), 39, 71),
       ((SELECT id FROM monster WHERE name = 'Psyduck'), 19, 43),
       ((SELECT id FROM monster WHERE name = 'Golduck'), 67, 169),
       ((SELECT id FROM monster WHERE name = 'Mankey'), 20, 62),
       ((SELECT id FROM monster WHERE name = 'Primeape'), 39, 71),
       ((SELECT id FROM monster WHERE name = 'Growlithe'), 28, 42),
       ((SELECT id FROM monster WHERE name = 'Arcanine'), 75, 342),
       ((SELECT id FROM monster WHERE name = 'Poliwag'), 24, 27),
       ((SELECT id FROM monster WHERE name = 'Poliwhirl'), 39, 44),
       ((SELECT id FROM monster WHERE name = 'Poliwrath'), 51, 119),
       ((SELECT id FROM monster WHERE name = 'Abra'), 35, 43),
       ((SELECT id FROM monster WHERE name = 'Kadabra'), 51, 125),
       ((SELECT id FROM monster WHERE name = 'Alakazam'), 59, 106),
       ((SELECT id FROM monster WHERE name = 'Machop'), 31, 43),
       ((SELECT id FROM monster WHERE name = 'Machoke'), 59, 155),
       ((SELECT id FROM monster WHERE name = 'Machamp'), 63, 287),
       ((SELECT id FROM monster WHERE name = 'Bellsprout'), 28, 9),
       ((SELECT id FROM monster WHERE name = 'Weepinbell'), 39, 14),
       ((SELECT id FROM monster WHERE name = 'Victreebel'), 67, 34),
       ((SELECT id FROM monster WHERE name = 'Tentacool'), 35, 100),
       ((SELECT id FROM monster WHERE name = 'Tentacruel'), 63, 121),
       ((SELECT id FROM monster WHERE name = 'Geodude'), 16, 44),
       ((SELECT id FROM monster WHERE name = 'Graveler'), 39, 232),
       ((SELECT id FROM monster WHERE name = 'Golem'), 55, 662),
       ((SELECT id FROM monster WHERE name = 'Ponyta'), 39, 66),
       ((SELECT id FROM monster WHERE name = 'Rapidash'), 67, 209),
       ((SELECT id FROM monster WHERE name = 'Slowpoke'), 47, 79),
       ((SELECT id FROM monster WHERE name = 'Slowbro'), 63, 173),
       ((SELECT id FROM monster WHERE name = 'Magnemite'), 12, 13),
       ((SELECT id FROM monster WHERE name = 'Magneton'), 39, 132),
       ((SELECT id FROM monster WHERE name = 'Farfetch''d'), 31, 33),
       ((SELECT id FROM monster WHERE name = 'Doduo'), 55, 86),
       ((SELECT id FROM monster WHERE name = 'Dodrio'), 71, 188),
       ((SELECT id FROM monster WHERE name = 'Seel'), 43, 198),
       ((SELECT id FROM monster WHERE name = 'Dewgong'), 67, 265),
       ((SELECT id FROM monster WHERE name = 'Grimer'), 35, 66),
       ((SELECT id FROM monster WHERE name = 'Muk'), 47, 66),
       ((SELECT id FROM monster WHERE name = 'Shellder'), 12, 9),
       ((SELECT id FROM monster WHERE name = 'Cloyster'), 59, 292),
       ((SELECT id FROM monster WHERE name = 'Gastly'), 51, 0.2),
       ((SELECT id FROM monster WHERE name = 'Haunter'), 63, 0.2),
       ((SELECT id FROM monster WHERE name = 'Gengar'), 59, 89),
       ((SELECT id FROM monster WHERE name = 'Onix'), 346, 463),
       ((SELECT id FROM monster WHERE name = 'Drowzee'), 39, 71),
       ((SELECT id FROM monster WHERE name = 'Hypno'), 63, 167),
       ((SELECT id FROM monster WHERE name = 'Krabby'), 16, 14),
       ((SELECT id FROM monster WHERE name = 'Kingler'), 51, 132),
       ((SELECT id FROM monster WHERE name = 'Voltorb'), 20, 23),
       ((SELECT id FROM monster WHERE name = 'Electrode'), 47, 147),
       ((SELECT id FROM monster WHERE name = 'Exeggcute'), 16, 6),
       ((SELECT id FROM monster WHERE name = 'Exeggutor'), 79, 265),
       ((SELECT id FROM monster WHERE name = 'Cubone'), 16, 14),
       ((SELECT id FROM monster WHERE name = 'Marowak'), 39, 99),
       ((SELECT id FROM monster WHERE name = 'Hitmonlee'), 59, 110),
       ((SELECT id FROM monster WHERE name = 'Hitmonchan'), 55, 111),
       ((SELECT id FROM monster WHERE name = 'Lickitung'), 47, 144),
       ((SELECT id FROM monster WHERE name = 'Koffing'), 24, 2),
       ((SELECT id FROM monster WHERE name = 'Weezing'), 47, 21),
       ((SELECT id FROM monster WHERE name = 'Rhyhorn'), 39, 254),
       ((SELECT id FROM monster WHERE name = 'Rhydon'), 75, 265),
       ((SELECT id FROM monster WHERE name = 'Chansey'), 43, 76),
       ((SELECT id FROM monster WHERE name = 'Tangela'), 39, 77),
       ((SELECT id FROM monster WHERE name = 'Kangaskhan'), 87, 176),
       ((SELECT id FROM monster WHERE name = 'Horsea'), 16, 18),
       ((SELECT id FROM monster WHERE name = 'Seadra'), 47, 55),
       ((SELECT id FROM monster WHERE name = 'Goldeen'), 24, 33),
       ((SELECT id FROM monster WHERE name = 'Seaking'), 51, 86),
       ((SELECT id FROM monster WHERE name = 'Staryu'), 19, 76),
       ((SELECT id FROM monster WHERE name = 'Starmie'), 43, 176),
       ((SELECT id FROM monster WHERE name = 'Mr. Mime'), 51, 120),
       ((SELECT id FROM monster WHERE name = 'Scyther'), 59, 123),
       ((SELECT id FROM monster WHERE name = 'Jynx'), 55, 90),
       ((SELECT id FROM monster WHERE name = 'Electabuzz'), 43, 66),
       ((SELECT id FROM monster WHERE name = 'Magmar'), 51, 98),
       ((SELECT id FROM monster WHERE name = 'Pinsir'), 59, 121),
       ((SELECT id FROM monster WHERE name = 'Tauros'), 55, 195),
       ((SELECT id FROM monster WHERE name = 'Magikarp'), 35, 22),
       ((SELECT id FROM monster WHERE name = 'Gyarados'), 256, 518),
       ((SELECT id FROM monster WHERE name = 'Lapras'), 98, 485),
       ((SELECT id FROM monster WHERE name = 'Ditto'), 12, 9),
       ((SELECT id FROM monster WHERE name = 'Eevee'), 12, 14),
       ((SELECT id FROM monster WHERE name = 'Vaporeon'), 39, 64),
       ((SELECT id FROM monster WHERE name = 'Jolteon'), 31, 54),
       ((SELECT id FROM monster WHERE name = 'Flareon'), 35, 55),
       ((SELECT id FROM monster WHERE name = 'Porygon'), 31, 80),
       ((SELECT id FROM monster WHERE name = 'Omanyte'), 16, 17),
       ((SELECT id FROM monster WHERE name = 'Omastar'), 39, 77),
       ((SELECT id FROM monster WHERE name = 'Kabuto'), 20, 25),
       ((SELECT id FROM monster WHERE name = 'Kabutops'), 51, 89),
       ((SELECT id FROM monster WHERE name = 'Aerodactyl'), 71, 130),
       ((SELECT id FROM monster WHERE name = 'Snorlax'), 83, 1014),
       ((SELECT id FROM monster WHERE name = 'Articuno'), 67, 122),
       ((SELECT id FROM monster WHERE name = 'Zapdos'), 63, 116),
       ((SELECT id FROM monster WHERE name = 'Moltres'), 79, 132),
       ((SELECT id FROM monster WHERE name = 'Dratini'), 71, 7),
       ((SELECT id FROM monster WHERE name = 'Dragonair'), 157, 36),
       ((SELECT id FROM monster WHERE name = 'Dragonite'), 87, 463),
       ((SELECT id FROM monster WHERE name = 'Mewtwo'), 79, 269),
       ((SELECT id FROM monster WHERE name = 'Mew'), 16, 9);
